# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 05:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('station_id', models.CharField(max_length=32, unique=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default='POINT (0 0)', srid=4326)),
                ('station_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='대여소 이름')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StateCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('parking_bike_tot_cnt', models.IntegerField(db_index=True, verbose_name='현재 주차 수')),
                ('rack_tot_cnt', models.IntegerField(db_index=True, verbose_name='총 주차 가능수')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='bike.Center')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
