# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 05:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0007_deal_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(default=b'POINT (0 0)', srid=4326)),
                ('isRoadAddress', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('sigugun', models.CharField(max_length=32)),
                ('dongmyun', models.CharField(max_length=32)),
                ('rest', models.CharField(max_length=32)),
                ('sido', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='deal',
            name='point',
        ),
        migrations.AddField(
            model_name='deal',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='earth.Location'),
        ),
    ]
