# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0010_auto_20170606_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='earth.Deal'),
        ),
    ]
