# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0011_auto_20170606_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='deal',
        ),
        migrations.AddField(
            model_name='deal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='earth.Location'),
        ),
    ]
