# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0012_auto_20170606_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='earth.Location'),
        ),
    ]
