# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0013_auto_20170606_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together=set([('sum_amount', 'dong', 'bldg_nm', 'deal_yy', 'deal_mm', 'deal_dd', 'bldg_area', 'aptfno')]),
        ),
    ]
