# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0014_auto_20170606_1708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together=set([]),
        ),
    ]
