# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0015_auto_20170606_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
