# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-24 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0017_deal_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-deal_yy', '-deal_mm', '-deal_dd']},
        ),
        migrations.AlterField(
            model_name='deal',
            name='bldg_nm',
            field=models.CharField(max_length=256, verbose_name='\uc544\ud30c\ud2b8'),
        ),
    ]
