# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0020_deal_area_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='newAddress',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
