# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-03 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0022_auto_20170629_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_mm',
            field=models.IntegerField(verbose_name='\uc6d4'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_yy',
            field=models.IntegerField(verbose_name='\ub144'),
        ),
    ]
