# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-05 10:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0023_auto_20170703_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='area_nm',
            field=models.CharField(default='', max_length=32, verbose_name='지역이름'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='bldg_area',
            field=models.FloatField(max_length=32, verbose_name='전용면적'),
        ),
        migrations.AlterField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT (0 0)', srid=4326),
        ),
    ]
