# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0024_auto_20170805_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_dd',
            field=models.CharField(db_index=True, max_length=32, verbose_name='일'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_mm',
            field=models.IntegerField(db_index=True, verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_yy',
            field=models.IntegerField(db_index=True, verbose_name='년'),
        ),
    ]
