# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-16 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0025_auto_20170806_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={},
        ),
    ]
