# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-16 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_auto_20170805_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('username', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
